tcp/blueprints/teacher/__init__.py
#!/usr/bin/python

""" To document. """

from flask import Blueprint, render_template, request, redirect, session, url_for
from common import github_client
from common.access import get_current_user, teacher_restricted
from model import database
from model.exercice import Exercice
from model.exercice_issue import ExerciceIssue
from model.user import User

# Backend controller instance.
controller = Blueprint('teacher', __name__, template_folder='templates')

@controller.route('/dashboard')
@teacher_restricted
def dashboard():
    """ /teacher/dashboard endpoint """
    # TODO : Retrieve metadata.
    return render_template('teacher/dashboard.html', current=get_current_user())

@controller.route('/exercice')
@controller.route('/exercice/<int:exercice_id>')
@teacher_restricted
def view_exercice(exercice_id=None):
    """ /teacher/exercice endpoint

    :param exercice_id: Optional identifier of the exercice to display.
    """
    if exercice_id is not None:
        exercice = Exercice.query.filter_by(id=exercice_id).first_or_404()
        issues = ExerciceIssue.query.filter_by(exercice_id=exercice_id).all()
        return render_template('teacher/view_exercice.html', current=get_current_user(), exercice=exercice, issues=issues)
    return render_template('teacher/list_exercice.html', current=get_current_user(), exercices=Exercice.query.all())

@controller.route('/exercice/edit', methods=['GET', 'POST'])
@controller.route('/exercice/edit/<int:exercice_id>', methods=['GET', 'POST'])
@teacher_restricted
def edit_exercice(exercice_id=None):
    """ /teacher/exercice/edit endpoint
    
    :param id: Optional identifier of the exercice to edit.
    """
    exercice = Exercice()
    if exercice_id is not None:
        exercice = Exercice.query.filter_by(id=exercice_id).first_or_404()
    if request.method == 'POST':
        exercice.name = request.form.get('name')
        exercice.description = request.form.get('description')
        exercice.max_score = int(request.form.get('max_score'))
        database.session.add(exercice)
        database.session.commit()
        return redirect(url_for('.view_exercice'))
    return render_template('teacher/edit_exercice.html', current=get_current_user(), exercice=exercice)

@controller.route('/exercice/<int:exercice_id>/issue/<int:issue_id>')
@teacher_restricted
def view_issue(exercice_id, issue_id):
    """ /teacher/exercice/<exercice_id>/issue/<issue_id> endpoint

    :param id: Optional identifier of the issue to display.
    """
    issue = ExerciceIssue.query.filter_by(id=issue_id, exercice_id=exercice_id).first_or_404()
    return render_template('teacher/view_issue.html', current=get_current_user(), issue=issue)
    
@controller.route('/exercice/<int:exercice_id>/issue/edit', methods=['GET', 'POST'])
@controller.route('/exercice/<int:exercice_id>/issue/edit/<int:issue_id>', methods=['GET', 'POST'])
@teacher_restricted
def edit_issue(exercice_id, issue_id=None):
    """ /teacher/exercice/<exercice_id>/issue/edit endpoint
    
    :param id: Optional identifier of the issue to edit.
    """
    issue = ExerciceIssue(exercice_id)
    if issue_id is not None:
        issue = ExerciceIssue.query.filter_by(id=issue_id, exercice_id=exercice_id).first_or_404()
    if request.method == 'POST':
        issue.exercice_id = exercice_id
        issue.name = request.form.get('name')
        issue.description = request.form.get('description')
        database.session.add(issue)
        database.session.commit()
        return redirect(url_for('.view_exercice', exercice_id=exercice_id))
    return render_template('teacher/edit_issue.html', current=get_current_user(), issue=issue)

tcp/blueprints/teacher/templates/teacher/dashboard.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="content">
                    <h3>Bienvenue {{ current.name }}</h3><br/>
                    <table class="table-menu">
                        <tr>
                            <td><i class="fa fa-database" aria-hidden="true"></i></td>
                            <td><a href="{{ url_for('teacher.view_exercice') }}">Exercice</a></td>
                        </tr>
                        <tr>
                            <td><i class="fa fa-user" aria-hidden="true"></i></td>
                            <td>Student</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/teacher/edit_exercice.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <div class="content">
                <form method="POST">
                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" class="form-control" placeholder="Nom du TP" name="name" value="{{ exercice.name }}" />
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" placeholder="Description" rows="3" name="description">{{ exercice.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="name">Score</label>
                        <input type="number" class="form-control" placeholder="Score" name="max_score" value="{{ exercice.max_score }}" />
                    </div>
                    <button type="submit" class="btn btn-default">Sauvegarder</button>
                </form>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/teacher/edit_issue.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <div class="content">
                <form method="POST">
                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" class="form-control" placeholder="Nom de l'issue" name="name" value="{{ issue.name }}" />
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" placeholder="Description" rows="3" name="description">{{ issue.description }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Sauvegarder</button>
                </form>
            </div>
        </div>
      </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/teacher/list_exercice.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="content">
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_exercice') }}" role="button">Nouveau TP</a>
                    <hr></hr>
                    {% if exercices|length == 0 %}
                        <p class="no-item">Aucun TP disponible.</p>
                    {% else %}
                        <table class="table table-striped">
                            <thead class="thead-inverse">
                                <tr>
                                    <td>Exercice</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for exercice in exercices %}
                                <tr>
                                    <td><a href="{{ url_for('teacher.view_exercice', exercice_id=exercice.id) }}">{{ exercice.name }}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/teacher/view_exercice.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="content">
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_exercice', exercice_id=exercice.id) }}" role="button">Modifier</a>
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_issue', exercice_id=exercice.id) }}" role="button">Ajouter une issue</a>
                    <hr></hr>
                    <div class="exercice-name">
                        <h3>{{ exercice.name }}</h3>
                    </div>
                    <div class="exercice-description">
                        <p>{% filter markdown %}{{ exercice.description }}{% endfilter %}</p>
                    </div>
                    <div class="exercice-score">
                        <p class="text-success">Score : {{ exercice.max_score }}</p>
                    </div>
                    <hr></hr>                    
                    {% if issues|length == 0 %}
                        <p class="no-item">Aucune issue pour ce TP</p>
                    {% else %}
                        <table class="table table-striped">
                            <thead class="thead-inverse">
                            <tr>
                                <td>Issues</td>
                            </tr>
                            </thead>
                            <tbody>
                                {% for issue in issues %}
                                <tr>
                                    <td><a href="{{ url_for('teacher.view_issue', exercice_id=exercice.id, issue_id=issue.id) }}">{{ issue.name }}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/teacher/view_issue.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="content">
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_issue', issue_id=issue.id, exercice_id=issue.exercice_id) }}" role="button">Modifier</a>
                    <hr></hr>
                    <div class="exercice-name">
                        <h3>{{ issue.name }}</h3>
                    </div>
                    <div class="exercice-description">
                        <p>{% filter markdown %}{{ issue.description }}{% endfilter %}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tcp/blueprints/teacher/templates/view_exercice.html
{% extends "authenticated.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="content">
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_exercice', id=exercice.id) }}" role="button">Modifier</a>
                    <a class="btn btn-default" href="{{ url_for('teacher.edit_issue', exercice_id=exercice.id) }}" role="button">Ajouter une issue</a>
                    <hr></hr>
                    <div class="exercice-name">
                        <h3>{{ exercice.name }}</h3>
                    </div>
                    <div class="exercice-description">
                        <p>{% filter markdown %}{{ exercice.description }}{% endfilter %}</p>
                    </div>
                    <div class="exercice-score">
                        <p class="text-success">Score : {{ exercice.max_score }}</p>
                    </div>
                    <hr></hr>                    
                    {% if issues|length == 0 %}
                        <p class="no-item">Aucune issue pour ce TP</p>
                    {% else %}
                        <table class="table table-striped">
                            <thead class="thead-inverse">
                            <tr>
                                <td>Issues</td>
                            </tr>
                            </thead>
                            <tbody>
                                {% for issue in issues %}
                                <tr>
                                    <td><a href="{{ url_for('teacher.view_issue', exercice_id=exercice.id, issue_id=issue.id) }}">{{ exercice.name }}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}